### ISSUE TITLE
[Regression] iASL only throws errors on syntax errors

### ISSUE THREAD

**Issue by paulmenzel** [acpica/acpica#774]
There is a regression in version 20220331, that errors are ignored.

### 20211217

```
dsdt.asl    275:    64,,, PB00)
Error    6049 -     ^ Length is larger than Min/Max window
[…]
Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20211217
Copyright (c) 2000 - 2021 Intel Corporation

coreboot toolchain v2022-02-25_a0b8032279
ASL Input:     dsdt.asl -   52287 bytes   1458 keywords   3039 source lines

Compilation failed. 1 Errors, 0 Warnings, 46 Remarks
[…]
```

### 20220331

```
[…]
    IASL       /cb-build/coreboot-gerrit.0/default/LENOVO_X200/dsdt.aml
dsdt.asl    279:    64,,, PB00)
Error    6049 -     ^ Length is larger than Min/Max window
[…]
Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20220331
Copyright (c) 2000 - 2022 Intel Corporation

coreboot toolchain v2022-04-04_9a8d0a03db
ASL Input:     dsdt.asl -   52365 bytes   1459 keywords   3043 source lines
AML Output:    dsdt.aml -   15076 bytes    833 opcodes     626 named objects

Compilation successful. 0 Errors, 0 Warnings, 29 Remarks, 537 Optimizations, 9 Constants Folded
    IASL       3150 warning types were ignored!
[…]
```

Link: https://review.coreboot.org/c/coreboot/+/64103

**Comment by ElyesH** [comment]
First bad commit found using git bisect:

commit 4fbd0d6fc5457353ddebe9ffd3cc316138825d5d
Author: Robert Moore <Robert.Moore@intel.com>
Date:   Fri Mar 18 09:51:22 2022 -0700

    Improve an iASL error message
    Add the filename to the Maximum error count exceeded message.

 source/compiler/aslcompile.c | 3 ++-
 source/compiler/aslerror.c   | 3 ++-
 2 files changed, 4 insertions(+), 2 deletions(-)

**Comment by ElyesH** [comment]
The issue is linked to "AslGbl_ExceptionCount[ASL_ERROR] = 0;"  2 lines

**Comment by acpibob** [comment]
Thanks for doing the bisect. We do have a fix for this.

**Comment by ElyesH** [comment]
Would you share the fix ?

**Comment by ElyesH** [comment]
Maybe 20221020 fix it.

**Comment by ElyesH** [comment]
Solved using version 20221020.
Would you close current issue?

**Comment by ElyesH** [comment]
Paul,
would you please close current issue?
20221020 solved the issue ( https://review.coreboot.org/c/coreboot/+/70856 )
Thank you

**Comment by paulmenzel** [comment]
@ElyesH, do you know what commit fixed it?

**Comment by ElyesH** [comment]
Change-Id: [I386a675](https://review.coreboot.org/q/I386a6757a318336bc616091afe0c4ed88cd89583)

**Comment by paulmenzel** [comment]
I meant what ACPICA commit.

**Comment by ElyesH** [comment]
oops, commit b24642ba

**Comment by paulmenzel** [comment]
Thank you for the analysis.

**Comment by ElyesH** [comment]
Humm, no; I'm not sure ...
