### PR TITLE
Fix segfault when error-checking mixed table types

### PR DESCRIPTION
**Pull request by myrade**
If a code table which contains errors is passed to iasl followed by a data table, AePrintErrorSourceLine will call FlGetFileHandle with an InFileId of ASL_FILE_SOURCE_OUTPUT and a non-NULL Filename.

When FlGetFileHandle searches AslGbl_FilesList, it first encounters the entry for the data table, which has no Files entry for this InFileId.

It then passes a NULL value to strcmp which can cause a segfault.

The bug was introduced in https://github.com/acpica/acpica/commit/997f6ca123771073a6f62738734a561d2dd056ac when FlGetFileHandle was added. Before, AePrintErrorSourceLine checked if AslGbl_Files[ASL_FILE_SOURCE_OUTPUT].Handle was NULL before proceeding.

Simple repro:
```
❯ ./iasl -T dsdt
Created ACPI table template for [DSDT], written to "dsdt.asl"
❯ ./iasl -T facp
Created ACPI table template for [FACP], written to "facp.asl"
❯ diff dsdt.asl dsdt-mod.asl
11a12
>         Return (ABCD)
❯ ./iasl dsdt-mod.asl facp.asl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20230628
Copyright (c) 2000 - 2023 Intel Corporation

zsh: segmentation fault  ./iasl dsdt-mod.asl facp.asl
```

Works properly if arg order is reversed:
```
❯ ./iasl facp.asl dsdt-mod.asl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20230628
Copyright (c) 2000 - 2023 Intel Corporation

dsdt-mod.asl     12:         Return (ABCD)
Error    6084 -  Object does not exist ^  (ABCD)

ASL Input:     dsdt-mod.asl -     337 bytes      2 keywords      0 source lines
Table Input:   facp.asl -    8217 bytes    149 fields      172 source lines
Binary Output: facp.aml -     276 bytes

Compilation failed. 1 Errors, 0 Warnings, 0 Remarks
No AML files were generated due to compiler error(s)
```

### CODE REVIEW

**Comment by sacdintel** [comment]
Hi Myra,

Thanks a lot for the contribution. Can you please share some test files as attachments to a comment if possible with some test cases? I just want to confirm those test cases and understand more if there is more future scope for similar improvements/fixes and moving forward how can we improve args ordering and document it! Thanks!

**Comment by sacdintel** [comment]
Thanks a lot Myra! I will need to spend some more time studying the flow and test out a few things and get back to you soon!

**Comment by sacdintel** [comment]
Hi Myra,

I am so sorry that it took me so long to get back to your PR due to numerous things all going on at the same time, but I have finally reproduced everything before and after your PR applied and can confirm that it works and looks good! This is definitely one of the best and most clever PRs I have reviewed and demonstrates that great impact can come from the smallest of code changes! Great job once again, hope you can inspire and empower other women in tech, especially when it comes to open-source software participation and contribution! Thanks!

- Saket

**Comment by sacdintel** [comment]
PR_887_before_patch_applied_failure_confirmation
PR_887_success_confirmation

**Comment by sacdintel** [comment]
Before vs after screenshots for confirmation in case anyone needs to look!
